name: Deploy Test Environment

on:
  workflow_dispatch:
  workflow_run:
    workflows:
      - Node.js CI
    types:
      - completed

jobs:
  deploy-test:
    runs-on:
      - self-hosted

    steps:
      - name: Deploy
        run: |
          echo "Runner: $RUNNER_NAME"
          hostname
          uname -a
          whoami